[package]
name = "pjrb"
version = "0.1.0"
authors = ["joris"]
build = "build.rs"

[dependencies.regex]
version = "0.2.1"

[dependencies]
lalrpop-util = { git = "https://github.com/nikomatsakis/lalrpop"}

[build-dependencies]
lalrpop = { git = "https://github.com/nikomatsakis/lalrpop"}

